# Global settings
global:
  nameOverride: ""
  fullnameOverride: ""

# Image configuration
image:
  repository: quay.io/pxworks/docling-serve
  tag: cpu
  pullPolicy: IfNotPresent

# Image pull secrets for private repositories
imagePullSecrets:
  - name: quay-registry-secret

# Container command configuration
command:
  enabled: true
  value: ["uv", "run", "--extra", "ui", "docling-serve", "run", "--host", "127.0.0.1", "--port", "5001", "--enable-ui"]

# Service configuration
service:
  type: ClusterIP
  port: 5001
  targetPort: 5001

# Ingress configuration
ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: ocr.k8s2.pxworks.co
      paths:
        - path: /
          pathType: Prefix
  tls: []
# Istio configuration
istio:
  enabled: true
  gateway:
    enabled: true
    name: docling-serve-gateway
    hosts:
      - ocr.k8s2.pxworks.co
    tls:
      enabled: false
      credentialName: docling-serve-tls
  virtualService:
    enabled: true
    timeout: 600s
  destinationRule:
    enabled: true
    connectionPool:
      tcp:
        maxConnections: 100
      http:
        http1MaxPendingRequests: 50
        maxRequestsPerConnection: 10
        h2MaxRequests: 100
        maxRetries: 3
        idleTimeout: 90s

# Resource configuration
resources:
  requests:
    cpu: 24000m
    memory: 4Gi
  limits:
    cpu: 31500m
    memory: 12Gi

# Node affinity configuration
nodeAffinity:
  enabled: true
  preferredNode: office-worker-8
  required: false  # Set to true to require specific node

# Autoscaling (disabled by default for single node preference)
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

# Replica count
replicaCount: 1

# Storage configuration
persistence:
  enabled: true
  storageClass: longhorn
  accessMode: ReadWriteOnce
  size: 10Gi
  annotations: {}

# Pod configuration
podAnnotations:
  sidecar.istio.io/proxyCPU: "100m"
  sidecar.istio.io/proxyMemory: "128Mi"

podSecurityContext: {}

securityContext: {}



# Proxy configuration
proxy:
  enabled: true
  httpProxy: "http://pxw:*YXoDq728gcz_z_rAnLhh3e._7KELCH4@10.0.90.54:3128"
  httpsProxy: "http://pxw:*YXoDq728gcz_z_rAnLhh3e._7KELCH4@10.0.90.54:3128"
  noProxy: "localhost,169.254.169.254/32,127.0.0.1,10.0.0.0/8,192.168.0.0/16,172.16.0.0/12,.svc,.cluster.local,office-worker-1,office-worker-2,office-worker-3,office-worker-4,office-worker-5,office-worker-6,office-worker-7,office-worker-8,office-worker-9,office-worker-10,metrics-monitoring,kube-state-metrics"
# Environment variables
env:
  # UV Settings
  uv:
    concurrentDownloads: 5
  # Arabic Correction Settings
  arabic:
    enabled: false
    ollamaHost: "http://localhost:11434"
    modelName: "command-r7b-arabic:latest"
    timeout: 300
    enableRemoteServices: false

  # OCRMyPDF Preprocessing Settings
  ocrmypdf:
    enabled: true
    deskew: true
    clean: true
    optimize: 2
    oversample: 200
    removeBackground: false
    forceOcr: true
    skipText: false
    redoOcr: false
    progressBar: false
    timeout: 600
    languageDetection: true
    maxFileSizeMb: 200
    failOnError: false
    fallbackOnFailure: true
    parallelProcessing: true
    cleanFinal: true
    verbosity: 1
    progressBarFriendly: true
    manageRootLogger: false

  # Uvicorn Settings
  uvicorn:
    reload: false
    host: "127.0.0.1"
    port: 5001
    logLevel: "info"
    workers: 16

  # Docling Serve Settings
  doclingServe:
    enableUi: true
    artifactsPath: ""
    apiHost: "127.0.0.1"
    maxDocumentTimeout: 86400
    maxSyncWait: 600

# Service Account
serviceAccount:
  create: true
  annotations: {}
  name: ""

# Namespace configuration
namespaceOverride: ""