# Production overrides
replicaCount: 1

image:
  tag: "cpu"
  pullPolicy: Always

resources:
  requests:
    cpu: 500m  # More aggressive CPU for production
    memory: 1Gi
  limits:
    cpu: 28
    memory: 150Gi

nodeAffinity:
  enabled: true
  preferredNode: office-worker-8
  required: true  # Require specific node in production

persistence:
  size: 10Gi  # Larger storage for production

env:
  uvicorn:
    logLevel: "warning"  # Less verbose logging
    workers: 4  # More workers for production

# Skip namespace creation since we created it manually
namespaceOverride: docling-serve

# Proxy settings for production
proxy:
  enabled: true
  # Values will inherit from main values.yaml unless overridden here

# istio:
#   gateway:
#     tls:
#       enabled: true
#       credentialName: ocr-tls-secret