# GPU-enabled version for better performance
version: '3.8'

services:
  docling-serve-gpu:
    build:
      context: .
      dockerfile: Dockerfile.runpod
      args:
        - BUILDKIT_PROGRESS=plain
    image: quay.io/docling/docling-serve:runpod
    container_name: docling-serve-gpu
    ports:
      - "5001:5001"
    volumes:
      - ./data:/app/data
      - tessdata:/usr/local/share/tessdata
      - .:/app

    # Use conditional command based on dev mode
    command: >
      sh -c "
        if [ \"$$DOCLING_DEV_MODE\" = \"true\" ]; then
          echo 'Starting in development mode...';
          uv run --extra ui --extra cu124 docling-serve dev --host 0.0.0.0 --port 5001 --enable-ui;
        else
          echo 'Starting in production mode...';
          uv run --extra ui --extra cu124 docling-serve run --host 0.0.0.0 --port 5001 --enable-ui;
        fi
      "
    
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu,compute,utility]

    restart: unless-stopped

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  tessdata:
    driver: local