version: '3.8'

services:
  docling-serve:
    build: .
    # Optionally specify image if desired:
    image: quay.io/pxworks/docling-serve:cpu
    container_name: docling-serve
    ports:
      - "5001:5001"
    volumes:
      - ./data:/app/data
      # - tessdata:/usr/local/share/tessdata

    command: >
      sh -c "
        if [ \"$$DOCLING_DEV_MODE\" = \"true\" ]; then
          echo 'Starting in development mode...';
          docling-serve dev --host 0.0.0.0 --port 5001 --enable-ui;
        else
          echo 'Starting in production mode...';
          docling-serve run --host 0.0.0.0 --port 5001 --enable-ui;
        fi
      "

    restart: unless-stopped

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  tessdata:
    driver: local