version: '3.8'

services:
  docling-serve-gpu:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    container_name: docling-serve-gpu

    ports:
      - "5001:5001"

    # your very long list of environment vars...
    environment:
      - DOCLING_DEV_MODE=${DOCLING_DEV_MODE:-true}
      # … all the others …
      - CUDA_VISIBLE_DEVICES=all
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility

    volumes:
      - ./data:/app/data
      - tessdata:/usr/local/share/tessdata
      - .:/app

    # <<< NEW: this is how you request GPUs in compose 3.8+ >>>
    device_requests:
      - driver: nvidia
        count: all
        capabilities: [ gpu, utility ]

    # <<< FIXED: use single $ for your env var >>>
    command: >
      sh -c '
        if [ "$DOCLING_DEV_MODE" = "true" ]; then
          echo "Starting in development mode...";
          uv run --extra ui --extra cu124 docling-serve dev \
             --host 0.0.0.0 --port 5001 --enable-ui;
        else
          echo "Starting in production mode...";
          uv run --extra ui --extra cu124 docling-serve run \
             --host 0.0.0.0 --port 5001 --enable-ui;
        fi
      '

    restart: unless-stopped

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  tessdata:
    driver: local