apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "docling-serve.fullname" . }}
  namespace: {{ include "docling-serve.namespace" . }}
  labels:
    {{- include "docling-serve.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "docling-serve.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "docling-serve.selectorLabels" . | nindent 8 }}
        version: v1
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
          {{- end }}
      {{- if .Values.nodeAffinity.enabled }}
      affinity:
        nodeAffinity:
          {{- if .Values.nodeAffinity.required }}
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - {{ .Values.nodeAffinity.preferredNode }}
          {{- else }}
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - {{ .Values.nodeAffinity.preferredNode }}
          {{- end }}
      {{- end }}
      serviceAccountName: {{ include "docling-serve.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.command.enabled }}
          command: {{ .Values.command.value | toJson }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "docling-serve.fullname" . }}-config
            {{- if .Values.proxy.enabled }}
            - configMapRef:
                name: {{ include "docling-serve.fullname" . }}-proxy
          {{- end }}
      {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: data-volume
              mountPath: /app/data
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: {{ include "docling-serve.fullname" . }}-data
      {{- end }}
