{{- if .Values.pullSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.pullSecret.name | default (printf "%s-pull-secret" (include "docling-serve.fullname" .)) }}
  namespace: {{ include "docling-serve.namespace" . }}
  labels:
    {{- include "docling-serve.labels" . | nindent 4 }}
  {{- with .Values.pullSecret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.pullSecret.dockerconfigjson | b64enc }}
{{- end }}